[build]
  publish = "build/web"
  command = "flutter build web --release --no-tree-shake-icons"

[build.environment]
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

