[build]
  publish = "build/web"
  command = "flutter config --enable-web && flutter pub get && flutter build web --release --no-tree-shake-icons --no-wasm-dry-run --dart-define=FLUTTER_WEB_USE_SKIA=true"

[build.environment]
  NODE_VERSION = "18"
  FLUTTER_VERSION = "3.16.0"

# Автоматический деплой при push в main
[build.processing]
  skip_processing = false

# Настройки для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Кэширование статических ресурсов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

