[build]
  publish = "build/web"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  NODE_VERSION = "18"
  FLUTTER_VERSION = "3.16.0"

# Автоматический деплой при push в main
[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

